version = 1

[merge]
delete_branch_on_merge = true
method = "squash"

[merge.message]
title = "pull_request_title" # default: "github_default"
body = "pull_request_body" # default: "github_default"

[approve]
auto_approve_usernames = ["zingimmick", "dependabot"]

[update]
always = true # default: false
require_automerge_label = false # default: true
ignored_usernames = ["dependabot", "renovate"]

